# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'Gemfile', 'Gemfile.lock']


# Site Settings
title: "ByteBay 2018: 100% warsztatów"
email: "hi@bytebay.pl"
description: "15/16 marca 2018. Gdańsk, Stadion Energa. 100% warsztatów, 100% praktyki - ByteBay 2018"
baseurl: ""
url: "http://bytebay.pl"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-111693074-1"
googleAnalyticsSiteUrl: "bytebay.pl"
siteVerification: "AdVx0n_bJDaqSQYME75if_DY851iZL5FHkodd6NuzMg"

# Organizer Info
organizerName: "GDG Lviv"
organizerAlternateName: "Google Developer Group Lviv"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "lviv@gdg.org.ua"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "bytebay, warsztaty, java, javascript, devops, Gdańsk, gdansk"
twitterAccount: "@bytebay"
socialImageSrcGooglePlus: "/img/seo/share-google-plus.png"
socialImageSrcTwitter: "/img/seo/share-twitter.png"
socialImageSrcFacebook: "/img/seo/share-facebook.png"

# Documents
c4pUrl: "http://goo.gl/ZeiXSe"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"
c4BannerText: "Call 4 Trainers"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Strona główna"}
 # - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/sessions/", text: "Tematy"}
 - {permalink: "/speakers/", text: "Trenerzy"}
 - {permalink: "/schedule/", text: "Agenda"}
 # - {permalink: "/team/", text: "Team"}
 # - {permalink: "/logistics/", text: "Logistics"}
 # - {permalink: "/hackathon/", text: "Hackathon"}
 - {permalink: "/#subscribe", text: "Nasz newsletter"}
bottomNavigationLinks:
 - {link: "/#tickets", text: "Bilety"}
 - {link: "http://goo.gl/ZeiXSe", text: "Call 4 Trainers"}
rightNavigationButtons:
 - {link: "http://goo.gl/ZeiXSe", text: "Call 4 Trainers"}
 - {link: "/#tickets", text: "Bilety"}

# Hero Block
heroImage: "gdansk-cropped.jpg"
heroTitle: "ByteBay 2018 - <typeout>"
eventDate: "15/16 marca 2018, Gdańsk - Stadion Energa"
typeoutTextValues: '"", "Warsztaty", "Networking", "Programowanie", "Agile"'
typeoutFallback: "100% Warsztatów"
heroButtons:
 - {link: "http://goo.gl/ZeiXSe", text: "Call 4 Trainers"}
 - {permalink: "/#tickets", text: "Bilety"}

# About Block
aboutTitle: "Co to jest ByteBay?"
aboutBlock:
 - {title: "Keynote", image: "conference.jpg", text: "Programowanie to nie tylko rozmowy o kodzie. Rozpocznijmy inaczej, inspirująco - spójrzmy na to co robimy z zupełnie innej perspektywy!" }
 - {title: "Warsztaty", image: "workshop.jpg", text: "100% praktycznej wiedzy przekazanej w warsztatowej formie. Bez zbędnej ściemy, nawijania - tylko kod, rozwiązania i doświadczenie." }
 - {title: "Deep dive", image: "hackathon.jpg", text: "Przez niektórych nazywane także <i>University Talks</i>. Ponad dwie godziny szczegółowego wykładu. Praktyka dla tych, co wolą słuchać niż robić." }
aboutTopicsTitle: "ByteBay to pełne spektrum tematów"
aboutTopicsLead: "Czego możesz się spodziewać na sesjach warsztatowych"
aboutTopics:
  - {title: "JVM, Java, Kotlin, Scala", text: "Nie tylko frameworki ale przede wszystkim zasady działania samej platformy JVM (maszyny wirtualnej) oraz języków na niej funkcjonujących"}
  - {title: "JavaScript, frontend", text: "Sprawny, nowoczesny, ergonomiczny i łatwy w utrzymaniu interfejs użytkoniwka. To co użytkownik widzi, jest równie ważne jak samo działanie aplikacji."}
  - {title: "Architektura, Domain Driven Design", text: "Budowanie i modelowanie systemów w oparciu o to co się dzieje w rzeczywistym świecie. Budujemy systemy monolityczne, rozproszone (mikro serwisowe)."}
  - {title: "Machine Learning, Sztuczna inteligencja", text: "To co się teraz dzieje w IT to jedno. To co będzie się działo za dekadę - to zupełnie inny paradygment. Uczenie maszynowe, AI to tematy które dają wgląd w to co robią najwięksi w branży."}
  - {title: "Infrastruktura, chmura, DevOps", text: "Aplikacja to jeden aspekt IT. Środowisko w którym aplikacja działa, to kolejny. Jak wdrażać (Docker, wirtualizacja, Kubernetes)? Gdzie wdrażać (chmura, PaaS, IaaS)? Która chmurę wybrać."}
  - {title: "Samorozwój programistów", text: "Sprawy techniczne to jedno, ale równie ważne jest kształtowanie umiejętności interpersonalnych, komunikacji, prezentowania pomysłów przed szerszym audytorium (czy programistów, czy  managerów)."}

# Statistic Block
statisticBlockImage: ""
statisticBlock:
 - {count: "250", specialCharacter: "+", info: "uczestników", detail: "z całej Polski"}
 - {count: "80", specialCharacter: "+", info: "godzin", detail: "warsztatów"}
 - {count: "30", specialCharacter: "+", info: "trenerów"}
 - {count: "8", specialCharacter: "", info: "równoległych ścieżek", detail: "oraz strefa relaksu"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Najlepsi trenerzy i szkoleniowcy"
rockstarSpeakersButtonText: "Zobacz wszystkich trenerów"

# Location Block
locationBlockTitle: "Lokalizacja"
eventLocationName: "Stadion Energa"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "Pokoleń Lechii Gdańsk 1"
eventAddressLocality: "Gdańsk"
eventAddressLocalityRegion: ""
eventPostalCode: "80-560"
eventAddressCountry: "Polska"
eventStartTime: "2018-03-15T9:00"
eventDoorTime: "09:00"
eventEndTime: "2014-03-16T17:00"
eventPlaceCoordinates: "54.3900786,18.6392969"
mapCenterCoordinates: "54.388915,18.630398"
mapMobileCenterCoordinates: "54.384854,18.636528"

# Venue Block
venueBlockTitle: "Stadion Energa"
venueBlockLeadText: "Stadion Energa to niemal nieograniczona liczba możliwych warsztatów i sesji <i>deep-dive</i> <br> w niesamowitej scenerii lóż biznesowych, sektorów VIP czy szatni piłkarskich"
venueBigImage: "stadion_1.jpg"
venueSmallImage1: "stadion_2.jpg"
venueSmallImage2: "stadion_3.jpg"
venueSmallImage3: "stadion_4.jpg"
venueTitle: "Niebywałe miejsce"
venueFeatures: ["Zupełnie inna przestrzeń szkoleniowa", "Strefa reklaksu", "Warsztaty w lożach i sky boxach."]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizatorzy"
partnersTitle: "Sponsorzy"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Newsletter"
subscribeAction: "https://formspree.io/kuba.marchwicki+bb-subscribe@gmail.com"
subscribeButton: "Zapisz się!"
subscribeInfo: "Powiadomimy Ciebie o rozpoczęciu rejestracji! <br /> Sprzedaż biletów rozpoczynamy w drugiej połowie stycznia 2018. Poza tym <b>nie spamujemy!</b>"

# Tickets Block
ticketsTitle: "Bilety"
ticketsInfo: "Sprzedaż biletów rozpoczynamy w drugiej połowie stycznia 2018 - bo przecież nikt nie kupuje kota w worku."
# ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 # - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=bytebay", icon: "twitter"}
 # - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdg.org.ua", text: "GDG.org.ua"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:lviv@gdg.org.ua", text: "lviv@gdg.org.ua"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: false

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
